version: '3'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: example
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/cEscolar
    ports:
      - '8200:8000'
    depends_on:
      - db